# Generated by Django 5.2.8 on 2025-11-28 03:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trainings', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='trainingmodule',
            name='displayed',
            field=models.CharField(default='', max_length=30, verbose_name='Короткое название'),
        ),
    ]
