# Generated by Django 5.2.8 on 2025-11-28 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trainings', '0002_trainingmodule_displayed'),
    ]

    operations = [
        migrations.AddField(
            model_name='trainingmodule',
            name='base_order',
            field=models.IntegerField(default=None, null=True, verbose_name='Базовый порядок модуля'),
        ),
    ]
