# Generated by Django 5.2.8 on 2025-11-28 15:42

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('languages', '0006_alter_userlanguagestreak_language'),
        ('trainings', '0003_trainingmodule_base_order'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='userlanguagetraining',
            unique_together={('user', 'order', 'language')},
        ),
    ]
