# Generated by Django 5.2.8 on 2025-11-12 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='verbalisuser',
            name='cur_language',
            field=models.IntegerField(blank=True, null=True, verbose_name='изучаемый язык'),
        ),
    ]
