# Generated by Django 5.2.8 on 2025-11-16 04:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_verbalisuser_cur_language'),
    ]

    operations = [
        migrations.AddField(
            model_name='verbalisuser',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='users_images', verbose_name='Фото'),
        ),
        migrations.AlterField(
            model_name='verbalisuser',
            name='cur_language',
            field=models.IntegerField(blank=True, null=True, verbose_name='Изучаемый язык'),
        ),
    ]
