# Generated by Django 5.2.8 on 2025-11-19 04:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_following'),
    ]

    operations = [
        migrations.AddField(
            model_name='following',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterUniqueTogether(
            name='following',
            unique_together={('following_user', 'followed_user')},
        ),
    ]
