# Generated by Django 5.2.8 on 2025-11-19 15:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('languages', '0002_alter_language_options'),
        ('users', '0005_following_created_at_alter_following_unique_together'),
    ]

    operations = [
        migrations.AlterField(
            model_name='verbalisuser',
            name='cur_language',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='languages.language', verbose_name='Изучаемый язык'),
        ),
    ]
