# Generated by Django 5.2.8 on 2025-11-19 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Language',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language', models.CharField(max_length=30, verbose_name='Язык')),
                ('slug', models.SlugField(verbose_name='Слаг')),
                ('icon', models.ImageField(blank=True, null=True, upload_to='language_images', verbose_name='Иконка')),
            ],
        ),
    ]
