# Generated by Django 5.2.8 on 2025-11-19 15:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('languages', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='language',
            options={'verbose_name': 'язык', 'verbose_name_plural': 'Языки'},
        ),
    ]
