# Generated by Django 5.2.8 on 2025-11-23 10:54

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('languages', '0003_userlanguagestreak'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='userlanguagestreak',
            unique_together={('user', 'language')},
        ),
    ]
