# Generated by Django 5.2.8 on 2025-11-23 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('languages', '0004_alter_userlanguagestreak_unique_together'),
    ]

    operations = [
        migrations.AddField(
            model_name='userlanguagestreak',
            name='last_updated',
            field=models.DateField(auto_now=True),
        ),
    ]
