# Generated by Django 5.2.8 on 2025-11-24 16:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('languages', '0005_userlanguagestreak_last_updated'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userlanguagestreak',
            name='language',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='languages.language'),
        ),
    ]
