# Generated by Django 5.2.8 on 2025-12-07 11:15

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('words', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='collection',
            options={'verbose_name': 'коллекция', 'verbose_name_plural': 'Коллекции'},
        ),
        migrations.AddField(
            model_name='collection',
            name='added_users',
            field=models.ManyToManyField(related_name='added_set', to=settings.AUTH_USER_MODEL),
        ),
    ]
