# Generated by Django 5.2.8 on 2025-12-07 11:20

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('words', '0002_alter_collection_options_collection_added_users'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='collection',
            name='added_users',
            field=models.ManyToManyField(null=True, related_name='added_set', to=settings.AUTH_USER_MODEL),
        ),
    ]
