# Generated by Django 5.2.8 on 2025-12-07 13:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('words', '0004_alter_collection_added_users_alter_collection_owner'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='collection',
            name='users',
        ),
        migrations.DeleteModel(
            name='CollectionRating',
        ),
    ]
