# Generated by Django 5.2.8 on 2026-01-07 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('words', '0005_remove_collection_users_delete_collectionrating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sentence',
            name='words',
            field=models.ManyToManyField(related_name='sentences', to='words.word', verbose_name='слова в предложении'),
        ),
    ]
